/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculogusbasesdedatos;

/**
 *
 * @author juank
 */
public class DatosDeLaTabla extends javax.swing.JFrame {

    String momentoApli;
    String dosis;

    public DatosDeLaTabla() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMomentApl = new javax.swing.JLabel();
        txtMomentApl = new javax.swing.JTextField();
        lblDosis = new javax.swing.JLabel();
        txtDosis = new javax.swing.JTextField();
        btnTerminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 246));
        setMinimumSize(new java.awt.Dimension(400, 246));
        setPreferredSize(new java.awt.Dimension(400, 246));
        getContentPane().setLayout(null);

        lblMomentApl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMomentApl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMomentApl.setText("Momento Apl");
        getContentPane().add(lblMomentApl);
        lblMomentApl.setBounds(40, 10, 110, 30);

        txtMomentApl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtMomentApl);
        txtMomentApl.setBounds(20, 40, 150, 30);

        lblDosis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDosis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDosis.setText("Dosis");
        getContentPane().add(lblDosis);
        lblDosis.setBounds(230, 10, 110, 30);

        txtDosis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtDosis);
        txtDosis.setBounds(210, 40, 150, 30);

        btnTerminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnTerminar);
        btnTerminar.setBounds(130, 140, 130, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        
        CalculoGusBaseDeDatos pasar = new CalculoGusBaseDeDatos();
        
        momentoApli = txtMomentApl.getText();
        dosis = txtDosis.getText();
        
        pasar.dosis = dosis;
        pasar.momentoApl = momentoApli;
        
        
        
        this.dispose();
    }//GEN-LAST:event_btnTerminarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosDeLaTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosDeLaTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosDeLaTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosDeLaTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosDeLaTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTerminar;
    private javax.swing.JLabel lblDosis;
    private javax.swing.JLabel lblMomentApl;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtMomentApl;
    // End of variables declaration//GEN-END:variables
}
