/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculogusbasesdedatos;

/**
 *
 * @author juank
 */
public class InicioCalculoGus extends javax.swing.JFrame {

    /**
     * Creates new form InicioCalculoGus
     */
    public InicioCalculoGus() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInicio = new javax.swing.JLabel();
        lblCultivo = new javax.swing.JLabel();
        cmbCultivo = new javax.swing.JComboBox<>();
        lblSuelo = new javax.swing.JLabel();
        lblTextura = new javax.swing.JLabel();
        cmbTextura = new javax.swing.JComboBox<>();
        lblPendiente = new javax.swing.JLabel();
        cmbPendiente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(757, 517));
        setMinimumSize(new java.awt.Dimension(757, 517));
        setPreferredSize(new java.awt.Dimension(757, 517));
        getContentPane().setLayout(null);

        lblInicio.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInicio.setText("Inicio");
        lblInicio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblInicio);
        lblInicio.setBounds(330, 20, 120, 60);

        lblCultivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCultivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCultivo.setText("Seleccione un cultivo");
        getContentPane().add(lblCultivo);
        lblCultivo.setBounds(10, 100, 140, 30);

        cmbCultivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbCultivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un opcion", "Alfalfa", "Girasol", "Maiz", "Soja", "Trigo" }));
        getContentPane().add(cmbCultivo);
        cmbCultivo.setBounds(160, 100, 150, 30);

        lblSuelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSuelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSuelo.setText("SUELO");
        getContentPane().add(lblSuelo);
        lblSuelo.setBounds(80, 150, 140, 30);

        lblTextura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTextura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTextura.setText("Textura");
        getContentPane().add(lblTextura);
        lblTextura.setBounds(10, 190, 140, 30);

        cmbTextura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbTextura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion", "Franco Arenoso", "Franco o Fr-Arc-Li", "Fr-Li o Fr-Arc o Li o Arc-Li" }));
        getContentPane().add(cmbTextura);
        cmbTextura.setBounds(160, 190, 150, 30);

        lblPendiente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPendiente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPendiente.setText("Pendiente");
        getContentPane().add(lblPendiente);
        lblPendiente.setBounds(10, 230, 140, 30);

        cmbPendiente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbPendiente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion", "< 2 %", "2 a 5 %", "> 5 %" }));
        getContentPane().add(cmbPendiente);
        cmbPendiente.setBounds(160, 230, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Mat. Orgánica");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 270, 140, 30);

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion", "< 5 %", "> 5 %" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(160, 270, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("pH");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 310, 140, 30);

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion", "< 5,0", "5,0 a 5,5", "5,5 a 6,0", "6,0 a 6,5", "> 6,5" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(160, 310, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Distancia al H2O");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 350, 140, 30);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion", "< 3 m", "3 a 6 m", "6 a 12 m", "> 12 m" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(160, 350, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CLIMA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 150, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Clima");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 190, 140, 30);

        jComboBox7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion", "Seco", "Humedo", "Templado" }));
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(500, 190, 150, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Terminar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 410, 180, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CalculoGusBaseDeDatos calculo = new CalculoGusBaseDeDatos();
        calculo.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioCalculoGus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioCalculoGus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioCalculoGus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioCalculoGus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioCalculoGus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCultivo;
    private javax.swing.JComboBox<String> cmbPendiente;
    private javax.swing.JComboBox<String> cmbTextura;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCultivo;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblPendiente;
    private javax.swing.JLabel lblSuelo;
    private javax.swing.JLabel lblTextura;
    // End of variables declaration//GEN-END:variables
}
